routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [\App\Http\Controllers\HomeController::class, 'home'])->name('/');
Route::get('/blog/{slug}', [\App\Http\Controllers\HomeController::class, 'BlogBySlug'])->name('BlogBySlug');
Route::get('/category/{slug}', [\App\Http\Controllers\HomeController::class, 'CategoryBySlug'])->name('CategoryBySlug');
Route::post('/subscribe', [\App\Http\Controllers\SubscribeController::class, 'subscribe'])->name('subscribe');
Route::get('/contact', function () {
    return view('pages.contact');
})->name('contact');
Route::get('/about', function () {
    return view('pages.about');
})->name('about');
Route::get('/search', [BlogController::class, 'search'])->name('search');
Route::post('/message/create', [\App\Http\Controllers\MessageController::class, 'create'])->name('message.create');
Route::get('policy', function () {
    return view('pages.policy');
})->name('policy');
Route::get('term', function () {
    return view('pages.term');
})->name('term');


Route::get('/categories', function () {
    return view('pages.categories');
})->name('categories');
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Route::resource('users', 'UserController');
    Route::resource('blogs', BlogController::class);
    // Route::resource('categories', 'CategoryController');
    // Route::resource('marks', 'MarkController');
});

require __DIR__ . '/auth.php';

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;
class Blog extends Model
{
    use HasFactory;

    protected $fillable = [
        'slug','title','introduction','body','conclusion','visits','mark_id','image',
        'meta_keywords',
        'meta_description',
        'viewport',
        'category_id'

    ];

    /*
    |------------------------------------------------------------------------------------
    | Validations
    |------------------------------------------------------------------------------------
    */
    public static function rules($update = false, $id=null)
    {
        return [
            'name' => 'required',
        ];
    }

    /*
    |------------------------------------------------------------------------------------
    | Relations
    |------------------------------------------------------------------------------------
    */

    public function mark(){
        return $this->belongsTo(Mark::class,'mark_id','id');
    }
    public function category(){
        return $this->hasone(Category::class,'id','category_id');
    }
    /*
    |------------------------------------------------------------------------------------
    | Scopes
    |------------------------------------------------------------------------------------
    */

    /*
    |------------------------------------------------------------------------------------
    | Attributes
    |------------------------------------------------------------------------------------
    */

    public function getImageAttribute($value)
    {
        if (!$value) {
            return URL::to('/storage/images') .'/'.'notfound.png';
        }

        return URL::to('/storage/images') .'/'.$value;
    }
    public function setImageAttribute($photo)
    {
        $full_name       = Str::random(16) . '.' . $photo->getClientOriginalExtension();
        $photo->storeAs('public/images/', $full_name);
        $this->attributes['image'] = $full_name ;
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = Str::slug($value);
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;
use App\Models\Blog;
use App\Models\User;
use App\Models\Mark;
use App\Models\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Model|object
     */
    public function getBySlug($slug){
        return Blog::with(['category','mark'])->where('slug',$slug)->first();
    }
    public function index()
    {
        $blogs = Blog::latest('updated_at')->paginate(1);
        return view('admin.blog.index', compact('blogs'));
    }
    public function search(Request $request)
    {
        $request->validate(['query'=>'required']);
        $query = $request['query'];

        $blogs = Blog::latest('updated_at')
            ->where('title','like','%'.$query.'%')
            ->orwhere('introduction','like','%'.$query.'%')
            ->orwhere('body','like','%'.$query.'%')
            ->orwhere('conclusion','like','%'.$query.'%')
            ->orwhere('meta_keywords','like','%'.$query.'%')
            ->orwhere('meta_description','like','%'.$query.'%')
            ->orwhere('introduction','like','%'.$query.'%')
            ->paginate(12);
        return view('pages.search', compact('blogs','query'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
         $marks =  Mark::all();
            // $marks_array = [];
            // foreach ($marks as $mark){
            //     $mars_array[$mark->id] = $mark->flag;
            // }

            $categories =  Category::all();
            // $categories_array = [];
            // foreach ($categories as $category){
            //     $categories_array[$category->id] = $category->name;
            // }

        return view('admin.blog.create',compact('marks','categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = $request->all();

        Blog::create($data);

        return back()->withSuccess(trans('app.success_store'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Blog::findOrFail($id);

        return view('admin.blogs.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $item = Blog::findOrFail($id);

        $data = $request->all();

        $item->update($data);

        return redirect()->route(ADMIN . '.blogs.index')->withSuccess(trans('app.success_update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Blog::destroy($id);

        return back()->withSuccess(trans('app.success_destroy'));
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/blog/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Blog') }}
        </h2>
    </x-slot>

    <div class="py-12 container mx-auto">
        <div class="bg-white p-10 mb-8   rounded-lg   md:mb-12 md:grid-cols-2">
            <form action="{{route('blogs.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                {{-- <div class="my-6">
                    <label for="default-input"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Slug</label>
                    <input type="text" name="slug" id="default-input"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm  focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                </div> --}}
                <div class="my-6">
                    <label for="default-input"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Title</label>
                    <input type="text" name="title" id="default-input"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm  focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                </div>
                <div class="my-6">
                    <label for="default-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Meta
                        Keywords</label>
                    <input type="text" name="meta_keywords" id="default-input"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm  focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                </div>
                <div class="my-6">
                    <label for="default-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Meta
                        Description</label>
                    <input type="text" name="meta_description" id="default-input"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm  focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                </div>
                <div class="my-6">
                    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="file_input">Base
                        Image</label>
                    <input name="image"
                        class="block w-full py-1 text-gray-900 border border-gray-300  cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
                        id="file_input" type="file">
                </div>
                @include('components.editor')
                <div class="my-6">

                <label for="category" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select an
                    category</label>
                <select id="category" name="category_id" 
                    class="bg-gray-50 border border-gray-300 text-gray-900   focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    @foreach ($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>

                    @endforeach
                </select>
                </div>
                <div class="my-6">

                    <label for="marks"   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select an
                        marks</label>
                    <select id="marks"  name="mark_id"
                        class="bg-gray-50 border border-gray-300 text-gray-900   focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        @foreach ($marks as $mark)
                        <option value="{{$mark->id}}">{{$mark->flag}}</option>
    
                        @endforeach
                    </select>
                    </div>
                    <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Save Blog</button>

            </form>
        </div>
    </div>
</x-app-layout>

resources/views/admin/blog/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Blog') }}
        </h2>
    </x-slot>

    <div class="py-12 container mx-auto">
        <a href="{{route('blogs.create')}}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">New Blog</a>

        <div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-5">
           

            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400 rounded ">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-5">
                            Slug
                        </th>
                        <th scope="col" class="px-6 py-5">
                            Title
                        </th>
                        <th scope="col" class="px-6 py-5">
                            Visits
                        </th>
                        <th scope="col" class="px-6 py-5">
                            Mark id
                        </th>
                        <th scope="col" class="px-6 py-5">
                            Category id
                        </th>
                        <th scope="col" class="px-6 py-5">
                            Created
                        </th>
                        <th scope="col" class="px-6 py-5">
                            Updated
                        </th>
                        <th scope="col" class="px-6 py-5">
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($blogs as $blog)
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{$blog->slug}}
                        </th>
                        <td class="px-6 py-4">
                            {{$blog->title}}
                        </td>
                        <td class="px-6 py-4">
                            {{$blog->visits}}
                        </td>
                        <td class="px-6 py-4">
                            {{$blog->mark_id}}                        
                        </td>
                        <td class="px-6 py-4">
                            {{$blog->category_id}}                        
                        </td>
                        <td class="px-6 py-4">
                            {{$blog->created_at}}
                        </td>
                        <td class="px-6 py-4">
                            {{$blog->updated_at}}
                        </td>
                        <td class="px-6 py-4">
                            <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                        </td>
                    </tr> 
                    @endforeach
                   
                  
                </tbody>

            </table>
        </div>
        {{$blogs->links()}}

    </div>
</x-app-layout>